### ISSUE TITLE
Elements 드래그 앤 드롭, 삭제 오류 & react-native style property & component delete not working

### ISSUE THREAD

**Issue by hyun12345** [CreadDiscans/ServiceDesigner#10]
1) 저장된 design.save.json 파일 불러와 어떤 component의 element tree 구조 변경 시 error 발생
=> 드래그 앤 드롭, 삭제에서 오류 발생

-오류 내용
![image](https://user-images.githubusercontent.com/41934505/59811743-32283380-9346-11e9-8f78-35aea105fdca.png)

2) ServiceDesigner에서 react-native style 수정할 때 적용 안 되는 property 존재
=> flex, flexDirection, justifyContent, alignItems 등

-style 적용 내용
![image](https://user-images.githubusercontent.com/41934505/59812207-1e7dcc80-9348-11e9-9688-3c07b1b6a337.png)

-ServiceDesigner 화면 출력 : 해당 View의 flex-direction:row 값이 적용되지 않아 한 줄에 출력되지 않음
![image](https://user-images.githubusercontent.com/41934505/59813387-2f304180-934c-11e9-8b78-06e2a5185855.png)

-Emulator 화면 출력 : 정상 출력 됨
![image](https://user-images.githubusercontent.com/41934505/59813556-ecbb3480-934c-11e9-9fc5-7ad0e351ede4.png)

3) component 관련
-delete not working
-component's name could be duplicated(=> causes error)

**Comment by CreadDiscans** [comment]
수정완료
