### ISSUE TITLE
component delete not working & issues about property style

### ISSUE THREAD

**Issue by hyun12345** [CreadDiscans/ServiceDesigner#11]
1) component delete not working

2) property style 
(1)'flex' not working
-각 View에 flex가 적용되어있는 component의 경우 ServiceDesigner에서 이처럼 출력됨
![image](https://user-images.githubusercontent.com/41934505/59897112-1e53fe80-9426-11e9-9de7-fa217825a494.png)

-최상위 View에 flex 적용하는 경우 Emulator에서도 이처럼 출력됨
![image](https://user-images.githubusercontent.com/41934505/59897156-578c6e80-9426-11e9-9003-f6c6be75e7c4.png)

(2)'position: absolute ㅣleft || right: n' not working at ServiceDesigner
-ServiceDesigner에서는 position:absoulte 적용되지 않은 상태로 출력됨
![image](https://user-images.githubusercontent.com/41934505/59901180-63cbf800-9435-11e9-825d-6753505c3d0c.png)

-Emulator: 정상 출력
![image](https://user-images.githubusercontent.com/41934505/59901209-7a724f00-9435-11e9-87f2-e10706f30abe.png)

(3)'flex-grow-' 'flex'와 마찬가지로 ServiceDesigner에서 출력될 때 적용되지 않은 상태로 출력됨
![image](https://user-images.githubusercontent.com/41934505/59900867-6843e100-9434-11e9-97db-e97ce6d02620.png)

**Comment by CreadDiscans** [comment]
수정 완료
