### ISSUE TITLE
property style 'height:xx%(percentage);' not working properly

### ISSUE THREAD

**Issue by hyun12345** [CreadDiscans/ServiceDesigner#12]
1. property style 'height: 100%(percentage);' not working properly at ServiceDesigner
1) ScrollView
(1) Scroll bar
*when height's value is 100%(percentage) => Scroll bar not printed
![image](https://user-images.githubusercontent.com/41934505/59984597-c35d1a00-9666-11e9-8b7d-572a7d5b4eed.png)

*when height's value is not percentage => Scroll bar printed
![image](https://user-images.githubusercontent.com/41934505/59984619-f43d4f00-9666-11e9-8a3c-5a0812aeefcf.png)

(2) flex-grow
*when height's value is 100%(percentage) => flex-grow not working properly at ServiceDesigner
![image](https://user-images.githubusercontent.com/41934505/59984955-4d0de700-9669-11e9-8fa4-143ef228ca7d.png)

*when height's value is not percentage => flex-grow working properly at ServiceDesigner
![image](https://user-images.githubusercontent.com/41934505/59984948-3798bd00-9669-11e9-92be-00cb90da1740.png)

2) View
(1)Other elements in View element
*when height's value is percentage
![image](https://user-images.githubusercontent.com/41934505/59984536-4cc01c80-9666-11e9-97c4-7f90c3356144.png)

*when height's value is not percentage
![image](https://user-images.githubusercontent.com/41934505/59984572-97da2f80-9666-11e9-8e0f-899f936bda4f.png)

(2) flex
*when height's value is percentage => flex not working properly at ServiceDesigner
![image](https://user-images.githubusercontent.com/41934505/59984964-5b5c0300-9669-11e9-8ced-b50aa1e5570e.png)

*when height's value is not percentage => flex working properly at ServiceDesigner
![image](https://user-images.githubusercontent.com/41934505/59984941-28197400-9669-11e9-9f6c-e921a1644a13.png)

**Comment by CreadDiscans** [comment]
height 100% 는 상위 태그를 기준으로 잡습니다.
display가 flex이면 contents 기준으로 height가 잡힙니다.
보여지는 화면을 기준으로 height를 잡을때는 height: 100vh로 써보세요
폭을 기준으로 할때는 100vw로 하면 됩니다.

**Comment by hyun12345** [comment]
react-native에서는 viewport unit(vw, vh, ...)을 사용하지 못하기 때문에
width, height에 각 값을 적용 시 ServiceDesigner에서는 정상 출력되지만
Emulator에서는 Unknown value 오류가 발생합니다.
1) ServiceDesigner
![image](https://user-images.githubusercontent.com/41934505/60061422-15b63d80-9730-11e9-8a3a-f274e4f76a57.png)

2) Emulator Unknown Error
![image](https://user-images.githubusercontent.com/41934505/60061457-3aaab080-9730-11e9-92b9-b71d6099b080.png)

* ServiceDesigner에서 Flex Dimensions 적용시 정상 적용 X
1) Flex Dimensions at react-native component
![image](https://user-images.githubusercontent.com/41934505/60061732-3f239900-9731-11e9-9df0-23b7362e84ca.png)

2) Flex Dimensions at ServiceDesigner component
(1) 4개의 View 생성한 뒤 parent View의 style 값 'flex:1;' 로 설정
![image](https://user-images.githubusercontent.com/41934505/60062002-4e571680-9732-11e9-9c46-eb9d45cac580.png)

(2) design.component.tsx에서 해당 component 확인하면 parent View 상위에 default 상태의 View element가 존재하여 정상적으로 출력되지 않음(ServiceDesigner & Emulator 모두) 
![image](https://user-images.githubusercontent.com/41934505/60062052-91b18500-9732-11e9-965a-a8418f9a2b05.png)

(3) 자동 생성되는 최상위 View 주석처리 시 Emulator에 정상 출력됨을 확인할 수 있음
![image](https://user-images.githubusercontent.com/41934505/60062116-cc1b2200-9732-11e9-8521-a3b0378469b7.png)

**Comment by CreadDiscans** [comment]
최상위 태그로 처리하는 대신에 배열처리방식으로 수정했습니다.
