### ISSUE TITLE
open file design.save.json => click component to modify : got error

### ISSUE THREAD

**Issue by hyun12345** [CreadDiscans/ServiceDesigner#13]
*got blank screen and error message
![image](https://user-images.githubusercontent.com/41934505/60558763-555ed400-9d85-11e9-86bd-b15af25bb66c.png)

*이전 파일인 designData.json 파일 열었을 때 정상 작동
![image](https://user-images.githubusercontent.com/41934505/60558848-9a830600-9d85-11e9-983a-54e3c559e904.png)
(정상적인 화면 출력 / 오류 발생 X)

**Comment by CreadDiscans** [comment]
수정완료
