### ISSUE TITLE
서비스 디자이너에서 Button 클릭시 내부에 화면이 하나 더 생김.

### ISSUE THREAD

**Issue by jongwon-park** [CreadDiscans/ServiceDesigner#14]
![image](https://user-images.githubusercontent.com/12497196/60636400-46ddee80-9e51-11e9-8ab6-725bc305d44f.png)

![image](https://user-images.githubusercontent.com/12497196/60636418-578e6480-9e51-11e9-9a51-6804836473d6.png)

**Comment by CreadDiscans** [comment]
내부에서 form이 submit 되면서 url 바뀌는 현상 막았습니다.
