### ISSUE TITLE
style property에 state 사용

### ISSUE THREAD

**Issue by hyun12345** [CreadDiscans/ServiceDesigner#26]
![image](https://user-images.githubusercontent.com/41934505/66731648-54186980-ee93-11e9-91f7-e75096348cbf.png)

![image](https://user-images.githubusercontent.com/41934505/66731662-64304900-ee93-11e9-8b2e-c4a0d7314bea.png)

style property 값으로 state 사용하기 위해 {} 입력하는 경우 이와 같은 오류 발생

**Comment by CreadDiscans** [comment]
reactstrap에 process써보세요
https://reactstrap.github.io/components/progress/
