### ISSUE TITLE
property에서 체크박스 클릭시 체크된 체크박스가 하나 더 생김.

### ISSUE THREAD

**Issue by jongwon-park** [CreadDiscans/ServiceDesigner#4]
![image](https://user-images.githubusercontent.com/12497196/57995943-beed9080-7aff-11e9-8583-a7f80105c6e5.png)

**Comment by CreadDiscans** [comment]
첫번째 체크박스는 해당 attribute를 활성화 할지 이고
두번째 체크박스는 활성화된 attribute의 값으로 state에 있는 변수를 사용할지 여부 입니다.
state에 사용 할 수 있는 변수가 없으면 두번체 체크박스는 체크할 수 없습니다.
