### ISSUE TITLE
Invariant Violation Error

### ISSUE THREAD

**Issue by hyun12345** [CreadDiscans/ServiceDesigner#5]
*service Designer로 생성한 design component에서 임의 class import했을 때 Inavariant Violation Error 발생

1. import design
1) ./theme/shared/splash.tsx
![image](https://user-images.githubusercontent.com/41934505/58148071-3b1adc00-7c98-11e9-91da-10a4455c0d97.png)

2) ./design.tsx
![image](https://user-images.githubusercontent.com/41934505/58149243-08bfad80-7c9d-11e9-8ffd-5b4c7da9d9d6.png)

3) InvariantViolation Error Msg
![image](https://user-images.githubusercontent.com/41934505/58148031-145ca580-7c98-11e9-89cd-dbc1cb61ba7f.png)

*비교테스트
react-native에서 생성한 InheritanceTest component에서 임의 class import했을 때 정상 작동

2. import InheritanceTest
1) ./theme/shared/InheritanceCallingTest.tsx
![image](https://user-images.githubusercontent.com/41934505/58148082-47069e00-7c98-11e9-87b2-054f7fcb70c7.png)

2) ./InheritanceTest.tsx
![image](https://user-images.githubusercontent.com/41934505/58149262-1e34d780-7c9d-11e9-8016-201884757c3f.png)

3) working
![image](https://user-images.githubusercontent.com/41934505/58148097-55ed5080-7c98-11e9-8290-2c5e5a7cfcc3.png)

**Comment by CreadDiscans** [comment]
DesignedXXX 클래스는 
class XXX extends DesignedXXX
처음 쓰도록 설계 되었습니다.

올려주신 에러는 Designer 보다는 React Native 설정에 관련된것 같네요
