### ISSUE TITLE
onPress : value / nested object array

### ISSUE THREAD

**Issue by hyun12345** [CreadDiscans/ServiceDesigner#6]
![image](https://user-images.githubusercontent.com/41934505/58304370-e362a900-7e2e-11e9-8a33-6afef52c9c39.png)

=> for문을 활용하여 Button / TouchableOpacity 생성 시 onPress로 event 값을 받아올 때 value의 값을 event가 아닌 item 값을 받아올 수 있을까요?

![image](https://user-images.githubusercontent.com/41934505/58531296-c9550c00-821c-11e9-8210-5f566bb82501.png)

=> TouchableOpacity e(event) key값과 e.value(event.value) key 값 출력 내용

 
 
 
 
 

![image](https://user-images.githubusercontent.com/41934505/58304726-6a645100-7e30-11e9-977e-9973b043ecc9.png)

=> object array 안에 object array가 있을 때 for문으로 한 값만 선택하여 반복 출력 가능한 것을 모든 값이 출력되도록 할 수 있을까요?
ex) this.state.dummyQ[i].list

**Comment by CreadDiscans** [comment]
=> for문을 활용하여 Button / TouchableOpacity 생성 시 onPress로 event 값을 받아올 때 value의 값을 event가 아닌 item 값을 받아올 수 있을까요?

 - name앞에 있는 두번째 체크 박스 체크하면 item에 있는 string변수를 지정할 수 있습니다. onPress에 name으로 해당 값을 받아옵니다.

=> object array 안에 object array가 있을 때 for문으로 한 값만 선택하여 반복 출력 가능한 것을 모든 값이 출력되도록 할 수 있을까요?

- array 속의 array도 variable에서 item기반으로 가져올 수 있도록 수정했습니다.

**Comment by CreadDiscans** [comment]
onPress와 같은 Event property에 두번째 체크박스를 추가했습니다.
체크시 item이 전달됩니다.
