### ISSUE TITLE
for loop onPress name value : 'item.name' error

### ISSUE THREAD

**Issue by hyun12345** [CreadDiscans/ServiceDesigner#7]
![image](https://user-images.githubusercontent.com/41934505/58606577-0bdb1f00-82d7-11e9-8a4a-bec62d6432c6.png)
ex) PlayerLeft for loop 적용된 버튼 name => item.name으로 설정

![image](https://user-images.githubusercontent.com/41934505/58606654-5e1c4000-82d7-11e9-8842-f27bb10a96d9.png)
=> 위 값이 설정된 해당 부분 design.tsx 코드
: onPress name의 값으로 'item.name' 문자열 값이 적용됨

![image](https://user-images.githubusercontent.com/41934505/58606675-742a0080-82d7-11e9-914b-da2173904943.png)
=> PlayerLeft component에서 onEvent에 Alert 설정하여 e.name 호출 및 출력

![image](https://user-images.githubusercontent.com/41934505/58606682-8015c280-82d7-11e9-9771-1de11877e8e2.png)
: name 의 값으로 문자열 값 'item.name' 그대로 출력됨

**Comment by CreadDiscans** [comment]
수정 완료
