### ISSUE TITLE
ServiceDesign Elements & Property & State

### ISSUE THREAD

**Issue by hyun12345** [CreadDiscans/ServiceDesigner#9]
* Elements

1) Elements 각 태그들을 기존 Layout에서처럼 상위 / 하위 위치 혹은 parent / child 관계가 될 수 있도록 수정하는 기능을 추가하면 elements 수정이 보다 용이해지지 않을까 생각합니다.

2) Elements를 전부 보이지지 않고, tree 구조 적용하여 수정 / 생성 시 필요한 elements만 하위까지 볼 수 있도록 하면 수정시 Elements 간의 관계를 더 쉽게 파악할 수 있지 않을까 생각합니다.

* Property

1) style : flex-direction: row; => 적용 X

- width & height 모두 100%인 View tag 안에서 flex-direction:row 적용 결과
![image](https://user-images.githubusercontent.com/41934505/59746089-11fa6500-92b1-11e9-9e1e-b5112d811c99.png)

* State

1) 새로운 component를 생성하여 State 값을 설정한 뒤 저장해도 state 값이 빈 값으로 저장되는 문제 발생(react-native)
2) 기존 state 값 수정하더라도 design.component.tsx에 수정된 사항 반영되어 저장되지 X

![image](https://user-images.githubusercontent.com/41934505/59749943-ee3b1d00-92b8-11e9-9ec9-92a8aff22720.png)

**Comment by CreadDiscans** [comment]
수정 완료
